[package]
name = "gonk-player"
version = "0.1.0"
edition = "2021"

authors = ["Bay"]
description = "Music playback library for gonk"
repository = "https://github.com/zX3no/gonk"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
# cpal = {git = "https://github.com/zX3no/cpal", path = "../.../cpal"}
symphonia = {version = "0.5.1", features = ["mp3", "isomp4", "alac", "aac"] }
gonk-database = {version = "0.1.0", path = "../gonk-database"}

[target.'cfg(unix)'.dependencies]
gag = "1.0.0"
alsa = "0.6"
nix = "0.24.1"
libc = "0.2.65"
jack = "0.10.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["audioclient", "combaseapi", "devpkey", "errhandlingapi", "handleapi", "ksmedia", "mmdeviceapi", "synchapi", "winbase"] }
once_cell = "1.12"