[package]
name = "gonk-player"
edition = "2021"
version = "0.0.1"

[dependencies]
cpal = "0.13.5"
gonk-core = { path = "../gonk-core" }
optick = "1.3.4"
rand = "0.8.5"
symphonia = { git="https://github.com/pdeljanov/Symphonia", features = ["aac", "mp3", "isomp4"] }
