[package]
name = "gronk-database"
version = "0.1.0"
edition = "2021"

[dependencies]
audiotags = "0.2.7182"
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
rayon = "1.5.1"
rusqlite = {version = "0.26.1", features = ["bundled"]}
walkdir = "2.3.2"
