[package]
name = "gronk-database"
version = "0.1.0"
edition = "2021"

[dependencies]
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
rayon = "1.5.1"
rusqlite = { version = "0.26.1", features = ["bundled"] }
gronk-types = {path = "../gronk-types"}
dirs = "4.0.0"
lazy_static = "1.4.0"
jwalk = "0.6.0"
