[package]
name = "gonk"
version = "0.1.2"
edition = "2021"
authors = ["Bay"]
description = "A terminal music player"
repository = "https://github.com/zX3no/gonk"
readme = "README.md"
license = "CC0-1.0"

default-run = "gonk"

[dependencies]
tui = "0.18.0"
crossterm = "0.23.2"
unicode-width = "0.1.9"
rayon = "1.5.3"
gonk-player = {version = "0.1.2", path = "../gonk-player"}
gonk-database = {version = "0.1.2", path = "../gonk-database"}
