[package]
name = "gonk"
version = "0.0.10"
edition = "2021"

authors = ["Bay"]
description = "A simple terminal music player"
repository = "https://github.com/zX3no/gonk"
readme = "../README.md"
license = "MIT"

[dependencies]
crossterm = "0.23.2"
tui = { version = "0.18.0", features = ["serde"] }
gonk-player = {version = "0.0.10", path = "../gonk-player"}
strsim = "0.10.0"
crossbeam-channel = "0.5.4"
unicode-width = "0.1.9"
rayon = "1.5.3"
serde = { version = "1.0.137", features = ["derive"] }
toml = {version = "0.5.9", features = ["preserve_order"]}
static_init = "1.0.2"
rusqlite = { version = "0.27.0", features = ["bundled"] }
dirs = "4.0.0"
jwalk = "0.6.0"
symphonia = "0.5.0"
miniserde = "0.1.24"
jsonxf = "1.1"

[target.'cfg(windows)'.dependencies]
global_hotkeys = "0.0.1"
