[package]
name = "gonk"
version = "0.0.3"
edition = "2021"

authors = ["Bay"]
description = "A simple terminal music player"
repository = "https://github.com/zX3no/gonk"
readme = "../README.md"
license = "MIT"

[dependencies]
crossterm = "0.23.2"
tui = { version = "0.17.0", features = ["serde"] }
gonk-core = {version = "0.0.2", path = "../gonk-core"}
gonk-player = {version = "0.0.2", path = "../gonk-player"}
strsim = "0.10.0"
static_init = "1.0.2"
crossbeam-channel = "0.5.4"

[target.'cfg(windows)'.dependencies]
global_hotkeys = "0.0.1"
