[package]
name = "gonk"
version = "0.0.1"
edition = "2021"
default-run = "gonk"
authors = ["Bay <example@email.com>"]

[dependencies]
crossterm = "0.22.1"
tui = { git = "https://github.com/zX3no/tui-rs",version = "0.16.0", default-features = false, features = ['crossterm'] }
# tui = {path = "../../tui-rs",version = "0.16.0", default-features = false, features = ['crossterm'] }
gonk-database = {path = "../gonk-database"}
gonk-types = {path = "../gonk-types"}
gonk-search = {path = "../gonk-search"}
rodio = {path = "../rodio"}
dirs = "4.0.0"
rand = "0.8.4"

[target.'cfg(windows)'.dependencies]
win-hotkey = { git = "https://github.com/zX3no/win-hotkey", rev ="1d6cb22ba202a445f73bf51a7e785655440639b3" }
