[package]
name = "gonk"
version = "0.0.8"
edition = "2021"

authors = ["Bay"]
description = "A simple terminal music player"
repository = "https://github.com/zX3no/gonk"
readme = "../README.md"
license = "MIT"

[dependencies]
crossterm = "0.23.2"
tui = { version = "0.18.0", features = ["serde"] }
gonk-core = {version = "0.0.8", path = "../gonk-core"}
gonk-player = {version = "0.0.8", path = "../gonk-player"}
strsim = "0.10.0"
crossbeam-channel = "0.5.4"
unicode-width = "0.1.9"

[target.'cfg(windows)'.dependencies]
global_hotkeys = "0.0.1"
