[package]
name = "gonk"
version = "0.0.10"
edition = "2021"
default-run = "gonk"

[dependencies]
crossterm = "0.23.2"
tui = "0.18.0"

rusqlite = { version = "0.27.0", features = ["bundled"] }
jwalk = "0.6.0"
rayon = "1.5.3"
static_init = "1.0.2"

gonk-player = {path = "../gonk-player"}
unicode-width = "0.1.9"

strsim = "0.10.0"
