[package]
name = "gonk-core"
version = "0.0.7"
edition = "2021"

authors = ["Bay"]
description = "Core types for gonk"
repository = "https://github.com/zX3no/gonk"
readme = "README.md"
license = "MIT"

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled"] }
dirs = "4.0.0"
static_init = "1.0.2"
jwalk = "0.6.0"
dpc-pariter = "0.5.1"
toml = "0.5.9"
serde = { version = "1.0.136", features = ["derive"] }
tui = { version = "0.18.0", features = ["serde"] }
crossterm = "0.23.2"
symphonia = "0.5.0"
r2d2_sqlite = "0.20.0"
r2d2 = "0.8.9"

[target.'cfg(windows)'.dependencies]
global_hotkeys = "0.0.1"
