[package]
name = "gonk-database"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.26.3", features = ["bundled"] }
gonk-types = {path = "../gonk-types"}
dirs = "4.0.0"
lazy_static = "1.4.0"
jwalk = "0.6.0"
dpc-pariter = "0.4.0"
